site_name: Fixes.co.za
site_url: https://fixes.co.za
repo_url: https://github.com/surfer190/fixes
site_description: Fixes.co.za is a repo of documentation, notes, summaries, fixes and solutions on software development and related topics
site_author: surfer190
theme:
  language: en
  name: material
  # turn off google fonts
  font: false
  icon:
    logo: material/book-open-page-variant
  favicon: img/favicon.ico
  palette:
    - scheme: default
      primary: pink
      accent: teal
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        primary: orange
        accent: green
        icon: material/lightbulb-outline
        name: Switch to light mode
  # highlightjs: true
  # hljs_style: github
  # nav_style: dark
  # prev_next_buttons_location: none
  # sticky_navigation: false
  collapse_navigation: true
  # custom_dir: custom_theme/
  include_search_page: true
markdown_extensions:
  - sane_lists
  - toc:
      permalink: "#"
      baselevel: 2
      separator: "_"
  - smarty
  - attr_list
  - meta
plugins:
  - search:
      min_search_length: 3
  - rss:
      date_from_meta:
        as_creation: "date"
        as_update: false
        datetime_format: "%Y-%m-%d"
use_directory_urls: true
extra:
  analytics:
    provider: custom