site_name: Fixes.co.za
site_url: https://fixes.co.za
repo_url: https://github.com/surfer190/fixes
edit_uri: ''
repo_name: fixes
site_description: Fixes.co.za is a repo of documentation, notes, summaries, fixes and solutions on software development and related topics
site_author: surfer190
theme:
  features:
    - navigation.tabs
  language: en
  name: material
  # turn off google fonts
  font: false
  icon:
    logo: material/book-open-page-variant
  favicon: img/favicon.ico
  palette:
    - scheme: default
      primary: pink
      accent: teal
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: orange
      accent: green
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  collapse_navigation: true
  custom_dir: overrides
  include_search_page: true
markdown_extensions:
  - sane_lists
  - toc:
      permalink: "#"
      baselevel: 2
      separator: "_"
  - smarty
  - attr_list
  - meta
plugins:
  - search:
      min_search_length: 3
  - rss:
      date_from_meta:
        as_creation: "date"
        as_update: false
        datetime_format: "%Y-%m-%d"
use_directory_urls: true
extra:
  analytics:
    provider: custom
extra_css:
  - stylesheets/extra.css
